/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-04-23 19:55:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.site.template.tp_005f02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<section id=\"agencia\">\n");
      out.write("\t\n");
      out.write("    <div class=\"container\">\n");
      out.write("    \t\n");
      out.write("        <h1>Quem Somos</h1>\n");
      out.write("        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sapien diam, consequat a tincidunt in, dapibus eget tellus. Quisque maximus malesuada ex, a porttitor nulla pellentesque a. Vivamus lobortis lectus at mi iaculis, varius pharetra nisl posuere. Aenean pretium leo sit amet massa molestie, ullamcorper congue ante molestie. Pellentesque tempus, orci at consectetur mollis, nisi urna rutrum lorem, et faucibus elit magna quis sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam sem mauris, tincidunt ac erat eget, elementum elementum lectus. Etiam consectetur, leo vel accumsan bibendum, nunc erat ornare metus, in efficitur eros nulla nec arcu. Vestibulum sed massa massa. Curabitur rutrum consectetur suscipit. Aliquam consectetur bibendum venenatis. Nunc in purus non magna varius aliquet. Duis condimentum velit sed fermentum imperdiet. Vestibulum imperdiet mauris sed libero bibendum sollicitudin.</p>\n");
      out.write("        <figure><img src=\"public/image/temp/agencia.jpg\" width=\"100%\" alt=\"nome da agência\"></figure>\n");
      out.write("        <br>\n");
      out.write("\t\t<p>Vestibulum gravida lectus et pretium euismod. Nulla facilisi. Vivamus vestibulum nisi quam, a elementum metus mollis in. Maecenas in nisl eu ex eleifend porta et vitae sapien. Aliquam cursus consectetur imperdiet. In hac habitasse platea dictumst. Curabitur interdum aliquam nulla vitae efficitur. Praesent et mauris id tortor interdum congue. Etiam eu nibh auctor, rhoncus felis ac, pretium nisi. Phasellus tempus tempus lorem consequat hendrerit. Etiam gravida orci vitae justo tristique, non porta eros efficitur. Etiam euismod scelerisque enim non vulputate. Duis mollis, ipsum vitae vestibulum auctor, libero mi scelerisque nulla, ac venenatis diam nisl eu augue.            </p>\n");
      out.write("\t\t\n");
      out.write("        <h2>Gostou da nossa Agência? Podemos encontrar o destino perfeito para você!</h2>\n");
      out.write("        <p><a href=\"destino-perfeito.php\" class=\"btn bg-thema\">DESTINO PERFEITO</a></p>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("</section>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
