/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-04-23 19:40:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.site.template.tp_005f02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<section id=\"contato\">\n");
      out.write("\t\n");
      out.write("    <div class=\"container\">\n");
      out.write("    \t\n");
      out.write("        <div class=\"col-1\">\n");
      out.write("            <h1>Contato</h1>    \n");
      out.write("            <p>Fusce quis nibh tempor, posuere sapien et, venenatis tortor mauris feugiat tempor magna, a accumsan purus molestie sed. </p>\n");
      out.write("            \n");
      out.write("            <form action=\"contato.php?alert=contato\" method=\"post\" name=\"form-contato\" class=\"form-contato\">\n");
      out.write("                <div class=\"box-1\">\n");
      out.write("                    <label for=\"nome\">*Nome:</label>\n");
      out.write("                    <input type=\"text\" class=\"input01\" name=\"nome\" id=\"nome\" placeholder=\"Nome Completo\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"box-1\">\n");
      out.write("                    <label for=\"email\">*E-mail:</label>\n");
      out.write("                    <input type=\"email\" class=\"input01\" name=\"email\" id=\"email\" placeholder=\"E-mail\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"box-2\">\n");
      out.write("                    <label for=\"telefone\">*Telefone:</label>\n");
      out.write("                    <input type=\"tel\" class=\"input01\" name=\"telefone\" id=\"telefone\" placeholder=\"Telefone: (00) 0000-0000\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"box-3\">\n");
      out.write("                    <label for=\"celular\">Celular:</label>\n");
      out.write("                    <input type=\"tel\" class=\"input01\" name=\"celular\" id=\"celular\" placeholder=\"Celular: (00) 0000-0000\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"box-1\">\n");
      out.write("                    <label for=\"mensagem\">*Mensagem:</label>\n");
      out.write("                    <textarea class=\"textarea01\" name=\"mensagem\" id=\"mensagem\" cols=\"5\" rows=\"5\"></textarea>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"box-1\">\n");
      out.write("                \t<button type=\"submit\" name=\"enviar\" class=\"submit01 bg-thema\"><i></i> ENVIAR MENSAGEM</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    \t\n");
      out.write("        \n");
      out.write("        <div class=\"col-2\">\n");
      out.write("        \t<!-- ENDEREÇO -->\n");
      out.write("        \t<div class=\"endereco\">\n");
      out.write("            \t<h2>Endereço</h2>\n");
      out.write("                <p>\n");
      out.write("                \t<i class=\"txt-thema\"></i>\n");
      out.write("                \tRua posuere sapien et, 365<br>\n");
      out.write("                \tLondrina - Paraná\n");
      out.write("                </p>\n");
      out.write("                \n");
      out.write("                <p><a href=\"#mapa\" onclick=\"$('html,body').animate({ scrollTop: $('#mapa').offset().top }, 1800);\" class=\"btn bg-thema\">VER NO MAPA</a></p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- TELEFONE -->\n");
      out.write("            <div class=\"telefone\">\n");
      out.write("            \t<h2>TELEFONE</h2>\n");
      out.write("                <p>\n");
      out.write("                \t<i class=\"txt-thema\"></i>\n");
      out.write("                    <a href=\"tel:04332589856\" class=\"link-telefone\"><small>(43)</small> 3258-9856</a>\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- E-MAIL -->\n");
      out.write("            <div class=\"email\">\n");
      out.write("            \t<h2>E-MAIL</h2>\n");
      out.write("                <p>\n");
      out.write("                \t<i class=\"txt-thema\"></i>\n");
      out.write("                \t<a href=\"mailto:contato@seusiteaqui.com.br\">contato@seusiteaqui.com.br</a>\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- MAPA -->\n");
      out.write("    <div id=\"mapa\" class=\"mapa-contato\"></div>\n");
      out.write("    <script type=\"text/javascript\" src=\"http://maps.google.com/maps/api/js?sensor=false\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("    $(document).ready(function () {\n");
      out.write("        (function() {\n");
      out.write("            if($('#mapa').length > 0) {            \n");
      out.write("                var map = new google.maps.Map(document.getElementById('mapa'), {\n");
      out.write("                    zoom : 16,\n");
      out.write("                    zoomControl: true,\n");
      out.write("                    scaleControl: true,\n");
      out.write("                    scrollwheel: false,\n");
      out.write("                    disableDoubleClickZoom: true,\n");
      out.write("                    center : new google.maps.LatLng(-23.3344613,-51.148428,15), //alterar coordenadas de endereço\n");
      out.write("                    mapTypeId : google.maps.MapTypeId.ROADMAP\n");
      out.write("                });\n");
      out.write("    \n");
      out.write("                var image = 'public/image/icons-location.png',\n");
      out.write("                    myLatLng = new google.maps.LatLng(-23.3344613,-51.148428,15); //alterar coordenadas de endereço\n");
      out.write("    \n");
      out.write("                var beachMarker = new google.maps.Marker({\n");
      out.write("                    position : myLatLng,\n");
      out.write("                    map : map,\n");
      out.write("                    icon : image\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        })();\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("    <!-- FIM MAPA -->\n");
      out.write("    \n");
      out.write("</section>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
