/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-04-23 19:55:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.site.template.tp_005f02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class onlineShop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<section id=\"compra\">\n");
      out.write("\t\n");
      out.write("    <div class=\"container\">\n");
      out.write("    \t\n");
      out.write("        <h1>Compra On-line</h1>    \n");
      out.write("\t\t\n");
      out.write("        <div class=\"coluna-1\">\n");
      out.write("        \n");
      out.write("            <ul class=\"categoria-compra\">\n");
      out.write("                <li class=\"hoteis bg-thema\"><a href=\"#\"><i></i><span>Hoteis</span></a></li>\n");
      out.write("                <li class=\"passagens bg-thema\"><a href=\"#\"><i></i><span>Passagens</span></a></li>\n");
      out.write("            </ul>\n");
      out.write("            \n");
      out.write("            <div class=\"forms-compra\">\n");
      out.write("                \n");
      out.write("                <!-- FORM HOTEIS --> \n");
      out.write("                <form action=\"#\" method=\"post\" name=\"form-compra\" class=\"form-compra border-thema\">\n");
      out.write("                    <p>Preencha os campos abaixo, nós lhe mostraremos os melhores preços e os horários de vôos das melhores companhias aéreas, depois é só escolher o melhor para você.</p>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-1\">\n");
      out.write("                      <label for=\"destino\">Destino</label>\n");
      out.write("                      <input type=\"text\" class=\"input01\" name=\"destino\" id=\"destino\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-2 data\">\n");
      out.write("                      <label for=\"entrada\">Entrada</label>\n");
      out.write("                      <input type=\"text\" class=\"input01\" name=\"entrada data\" id=\"entrada\" placeholder=\"99/99/9999\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-3 data\">\n");
      out.write("                      <label for=\"saida\">Saída</label>\n");
      out.write("                      <input type=\"text\" class=\"input01\" name=\"saida data\" id=\"saida\" placeholder=\"99/99/9999\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <h2>Quantidade de passageiros:</h2>\n");
      out.write("                    \n");
      out.write("                    <div class=\"qrt-hoteis\">\n");
      out.write("                    \t<div class=\"select-quartos\">\n");
      out.write("                        \t<label for=\"quartos\">Quantidade<br> de quartos:</label>\n");
      out.write("                            <select class=\"select01\" name=\"quartos\" id=\"quartos\">\n");
      out.write("                            \t<option value=\"0\">0</option>\n");
      out.write("                                <option value=\"1\">1</option>\n");
      out.write("                                <option value=\"2\">2</option>\n");
      out.write("                                <option value=\"3\">3</option>\n");
      out.write("                                <option value=\"4\">4</option>\n");
      out.write("                                <option value=\"5\">5</option>\n");
      out.write("                                <option value=\"6\">6</option>\n");
      out.write("                                <option value=\"7\">7</option>\n");
      out.write("                                <option value=\"8\">8</option>\n");
      out.write("                                <option value=\"9\">9</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"select-adultos\">\n");
      out.write("                        \t<label for=\"adultos\">Adultos: <small>(+12 anos)</small></label>\n");
      out.write("                            <select class=\"select01\" name=\"adultos\" id=\"adultos\">\n");
      out.write("                            \t<option value=\"0\">0</option>\n");
      out.write("                                <option value=\"1\">1</option>\n");
      out.write("                                <option value=\"2\">2</option>\n");
      out.write("                                <option value=\"3\">3</option>\n");
      out.write("                                <option value=\"4\">4</option>\n");
      out.write("                                <option value=\"5\">5</option>\n");
      out.write("                                <option value=\"6\">6</option>\n");
      out.write("                                <option value=\"7\">7</option>\n");
      out.write("                                <option value=\"8\">8</option>\n");
      out.write("                                <option value=\"9\">9</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"select-criancas\">\n");
      out.write("                        \t<label for=\"criancas\">Crianças: <small>(2 a 11 anos)</small></label>\n");
      out.write("                            <select class=\"select01\" name=\"criancas\" id=\"criancas\">\n");
      out.write("                            \t<option value=\"0\">0</option>\n");
      out.write("                                <option value=\"1\">1</option>\n");
      out.write("                                <option value=\"2\">2</option>\n");
      out.write("                                <option value=\"3\">3</option>\n");
      out.write("                                <option value=\"4\">4</option>\n");
      out.write("                                <option value=\"5\">5</option>\n");
      out.write("                                <option value=\"6\">6</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-1\">\n");
      out.write("                    \t<button type=\"submit\" name=\"enviar\" class=\"submit01 bg-thema\"><i></i> Buscar</button>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </form>\n");
      out.write("                \n");
      out.write("                <!-- FORM PASSAGENS --> \n");
      out.write("                <form action=\"#\" method=\"post\" name=\"form-compra\" class=\"form-compra border-thema\">\n");
      out.write("                    <p>Preencha os campos abaixo, nós lhe mostraremos os melhores preços e os horários de vôos das melhores companhias aéreas, depois é só escolher o melhor para você.</p>\n");
      out.write("                    <div>\n");
      out.write("                        <label class=\"label-radio\"><input name=\"n-passagem\" type=\"radio\" value=\"2\" checked> <span>Ida e Volta</span></label>\n");
      out.write("                        <label class=\"label-radio\"><input name=\"n-passagem\" type=\"radio\" value=\"1\" checked> <span>Ida</span></label>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-2\">\n");
      out.write("                      <label for=\"origem\">Origem</label>\n");
      out.write("                      <input type=\"text\" class=\"input01\" name=\"origem\" id=\"origem\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-3 data\">\n");
      out.write("                      <label for=\"ida\">Ida</label>\n");
      out.write("                      <input type=\"text\" class=\"input01 data\" name=\"ida\" id=\"ida\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-2\">\n");
      out.write("                      <label for=\"destino\">Destino</label>\n");
      out.write("                      <input type=\"text\" class=\"input01\" name=\"destino\" id=\"destino\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-3 data\">\n");
      out.write("                      <label for=\"volta\">volta</label>\n");
      out.write("                      <input type=\"text\" class=\"input01\" name=\"volta\" id=\"volta\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <h2>Quantidade de passageiros:</h2>\n");
      out.write("                    \n");
      out.write("                    <div class=\"qrt-passagens\">\n");
      out.write("                    \t<div class=\"select-adultos\">\n");
      out.write("                        \t<label for=\"adultos\">Adultos: <small>(+12 anos)</small></label>\n");
      out.write("                            <select class=\"select01\" name=\"adultos\" id=\"adultos\">\n");
      out.write("                            \t<option value=\"0\">0</option>\n");
      out.write("                                <option value=\"1\">1</option>\n");
      out.write("                                <option value=\"2\">2</option>\n");
      out.write("                                <option value=\"3\">3</option>\n");
      out.write("                                <option value=\"4\">4</option>\n");
      out.write("                                <option value=\"5\">5</option>\n");
      out.write("                                <option value=\"6\">6</option>\n");
      out.write("                                <option value=\"7\">7</option>\n");
      out.write("                                <option value=\"8\">8</option>\n");
      out.write("                                <option value=\"9\">9</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"select-criancas\">\n");
      out.write("                        \t<label for=\"criancas\">Crianças: <small>(2 a 11 anos)</small></label>\n");
      out.write("                            <select class=\"select01\" name=\"criancas\" id=\"criancas\">\n");
      out.write("                            \t<option value=\"0\">0</option>\n");
      out.write("                                <option value=\"1\">1</option>\n");
      out.write("                                <option value=\"2\">2</option>\n");
      out.write("                                <option value=\"3\">3</option>\n");
      out.write("                                <option value=\"4\">4</option>\n");
      out.write("                                <option value=\"5\">5</option>\n");
      out.write("                                <option value=\"6\">6</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"select-bebes\">\n");
      out.write("                        \t<label for=\"bebes\">Bebês: <small>(0 a 23 meses)</small></label>\n");
      out.write("                            <select class=\"select01\" name=\"bebes\" id=\"bebes\">\n");
      out.write("                            \t<option value=\"0\">0</option>\n");
      out.write("                                <option value=\"1\">1</option>\n");
      out.write("                                <option value=\"2\">2</option>\n");
      out.write("                                <option value=\"3\">3</option>\n");
      out.write("                                <option value=\"4\">4</option>\n");
      out.write("                                <option value=\"5\">5</option>\n");
      out.write("                                <option value=\"6\">6</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"box-1\">\n");
      out.write("                    \t<button type=\"submit\" name=\"enviar\" class=\"submit01 bg-thema\"><i></i> Buscar</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("\t\t\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"coluna-2\">\n");
      out.write("        \t<h2>Entre em contato</h2>\n");
      out.write("            <p>Morbi in libero sed turpis finibus egestas non sit amet dolor</p>\n");
      out.write("            <p class=\"telefone txt-thema\"><small>(43)</small> 6598-8458</p>\n");
      out.write("            <p class=\"email\"><a href=\"mailto:contato@seusiteaqui.com.br\">contato@seusiteaqui.com.br</a></p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("    </div>    \n");
      out.write("\n");
      out.write("\t<!-- AUTO COMPLETAR DE DESTINO -->\n");
      out.write("\t<script>\n");
      out.write("\t  $(function() {\n");
      out.write("\t\tvar availableTags = [\n");
      out.write("\t\t  \"Acre (AC)\",\n");
      out.write("\t\t  \"Alagoas (AL)\",\n");
      out.write("\t\t  \"Amapá (AP)\",\n");
      out.write("\t\t  \"Amazonas (AM)\",\n");
      out.write("\t\t  \"Bahia (BA)\",\n");
      out.write("\t\t  \"Ceará (CE)\",\n");
      out.write("\t\t  \"Distrito Federal (DF)\",\n");
      out.write("\t\t  \"Espírito Santo (ES)\",\n");
      out.write("\t\t  \"Goiás (GO)\",\n");
      out.write("\t\t  \"Maranhão (MA)\",\n");
      out.write("\t\t  \"Mato Grosso (MT)\",\n");
      out.write("\t\t  \"Mato Grosso do Sul (MS)\",\n");
      out.write("\t\t  \"Minas Gerais (MG)\",\n");
      out.write("\t\t  \"Pará (PA)\",\n");
      out.write("\t\t  \"Paraíba (PB)\",\n");
      out.write("\t\t  \"Paraná (PR)\",\n");
      out.write("\t\t  \"Pernambuco (PE)\",\n");
      out.write("\t\t  \"Piauí (PI)\",\n");
      out.write("\t\t  \"Rio de Janeiro (RJ)\",\n");
      out.write("\t\t  \"Rio Grande do Norte (RN)\",\n");
      out.write("\t\t  \"Rio Grande do Sul (RS)\",\n");
      out.write("\t\t  \"Rondônia (RO)\",\n");
      out.write("\t\t  \"Roraima (RR)\",\n");
      out.write("\t\t  \"Santa Catarina (SC)\",\n");
      out.write("\t\t  \"São Paulo (SP)\",\n");
      out.write("\t\t  \"Sergipe (SE)\",\n");
      out.write("\t\t  \"Tocantins (TO)\"\n");
      out.write("\t\t];\n");
      out.write("\t\t$( \"#destino, #origem\" ).autocomplete({\n");
      out.write("\t\t  source: availableTags\n");
      out.write("\t\t});\n");
      out.write("\t  });\n");
      out.write("\t</script>    \n");
      out.write("</section>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
