/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-04-13 19:15:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.protected_.staff;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listOfStaff_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- CONTENT -->\n");
      out.write("<!--TITLE -->\n");
      out.write("<div class=\"row\">\n");
      out.write("\t<div id=\"paper-top\">\n");
      out.write("\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t<!-- TITULO DA PÁGINA -->\n");
      out.write("\t\t\t<h2 class=\"tittle-content-header\">\n");
      out.write("\t\t\t\t<i class=\"icon-menu\"></i> <span>Gerenciar Equipe</span>\n");
      out.write("\t\t\t</h2>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--/ TITLE -->\n");
      out.write("\n");
      out.write("<!-- BREADCRUMB -->\n");
      out.write("<ul id=\"breadcrumb\">\n");
      out.write("\t<li><span class=\"entypo-home\"></span></li>\n");
      out.write("\t<li><i class=\"fa fa-lg fa-angle-right\"></i></li>\n");
      out.write("\t<li><a href=\"#\" title=\"Sample page 1\">Página Inicial</a></li>\n");
      out.write("\t<li><i class=\"fa fa-lg fa-angle-right\"></i></li>\n");
      out.write("\t<li><a href=\"#\" title=\"Sample page 1\">Gerenciar Equipe</a></li>\n");
      out.write("</ul>\n");
      out.write("<!-- FIM BREADCRUMB -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"content-wrap margin-bottom\">\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"nest text\">\n");
      out.write("\t\t\t<div class=\"title-alt\">\n");
      out.write("\t\t\t\t<h6>Equipe</h6>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\" class=\"form-filtro\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" id=\"filter\" placeholder=\"Procurar\"\n");
      out.write("\t\t\t\t\t\ttype=\"text\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t<select class=\"filter-status form-control\">\n");
      out.write("\t\t\t\t\t\t<option value=\"active\">Active</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"disabled\">Disabled</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"suspended\">Suspended</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t<a href=\"#clear\" style=\"margin-left: 10px;\"\n");
      out.write("\t\t\t\t\t\tclass=\"pull-right btn btn-info clear-filter\" title=\"clear filter\">Limpar</a>\n");
      out.write("\t\t\t\t\t<a href=\"#api\" class=\"pull-right btn btn-info filter-api\"\n");
      out.write("\t\t\t\t\t\ttitle=\"Filter using the Filter API\">Cadastro Novo</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\n");
      out.write("\t\t\t\t<table id=\"footable-res2\" class=\"demo margin-bottom\"\n");
      out.write("\t\t\t\t\tdata-filter=\"#filter\" data-filter-text-only=\"true\">\n");
      out.write("\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<th>Funcionário</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Departamento</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Ativo</th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t<!-- CONTEUDO DE TABLE -->\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>Carlos Afonso</td>\n");
      out.write("\t\t\t\t\t\t\t<td>Venda</td>\n");
      out.write("\t\t\t\t\t\t\t<td><div class=\"make-switch\" data-on=\"info\"\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-off=\"success\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" checked>\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>Rosane Braga</td>\n");
      out.write("\t\t\t\t\t\t\t<td>Venda</td>\n");
      out.write("\t\t\t\t\t\t\t<td><div class=\"make-switch\" data-on=\"info\"\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-off=\"success\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" checked>\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>Carla Ishimura</td>\n");
      out.write("\t\t\t\t\t\t\t<td>Venda</td>\n");
      out.write("\t\t\t\t\t\t\t<td><div class=\"make-switch\" data-on=\"info\"\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-off=\"success\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\">\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
